version: '3.8'

services:

  downstream-fake:
    build: ./downstream-fake
    ports:
      - "8081:8081"
    networks:
      - poc-net

  mulesoft-fake:
    build: ./mulesoft-fake
    ports:
      - "8082:8082"
    networks:
      - poc-net
    depends_on:
      - downstream-fake

  service-order:
    build: ./service-order
    ports:
      - "8080:8080"
    networks:
      - poc-net
    depends_on:
      - mulesoft-fake
      - downstream-fake
    environment:
      - JAVA_OPTS=-Xmx512m

networks:
  poc-net:
    driver: bridge
