server.port=8080
spring.mvc.static-path-pattern=/**
spring.application.name=service-order

mulesoft.url=http://localhost:8082
downstream.url=http://localhost:8081

# Sentinel Token Server
sentinel.server.url=http://localhost:8721
sentinel.server.host=localhost

# Sentinel Dashboard
spring.cloud.sentinel.transport.dashboard=localhost:8858
spring.cloud.sentinel.transport.port=8719
spring.cloud.sentinel.eager=true
