server.port=8721
spring.application.name=sentinel-token-server

# Namespace mặc định phục vụ (khớp với spring.application.name của client)
sentinel.namespace=service-order

# Kết nối lên Sentinel Dashboard
csp.sentinel.dashboard.server=localhost:8858
